server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: prep-engine
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com/v1
      chat:
        options:
          model: gpt-3.5-turbo
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [email, profile]
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  jwt:
    secret: 6ceb0b8c3eb251de22d044973b994c0a1069e52fcdeb324a541b29e57a45f3ee
    expiration: 86400000  # 1 day in ms

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: praxium
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.nclexportal: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG