server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: prep-engine

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: praxium
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.nclexportal: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG